-- wiki_members: users who have been invited to collaborate on a wiki
CREATE TABLE IF NOT EXISTS wiki_members (
  wiki_id   UUID NOT NULL REFERENCES wikis(id) ON DELETE CASCADE,
  user_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (wiki_id, user_id)
);

-- share_codes: one permanent invite code per wiki (generated by owner)
CREATE TABLE IF NOT EXISTS share_codes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  wiki_id    UUID NOT NULL UNIQUE REFERENCES wikis(id) ON DELETE CASCADE,
  code       VARCHAR(8) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
